### ISSUE TITLE
dockerコンテナ立ち上げた時にModuleNotFoundError: No module named 'asgiref.local'発生

### ISSUE THREAD

**Issue by infinity0206** [infinity0206/ChatApp#1]
下記エラーが発生する模様
```
C:\Users\infinity0206\Documents\ChatApp>docker-compose up
Starting chatapp_redis_1 ... done                                                                                       Starting chatapp_mysql_1 ... done                                                                                       Starting chatapp_django_1 ... done                                                                                      Starting chatapp_nginx_1  ... done                                                                                      Attaching to chatapp_redis_1, chatapp_mysql_1, chatapp_django_1, chatapp_nginx_1
redis_1   | 1:C 22 Mar 2020 09:48:53.493 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1   | 1:C 22 Mar 2020 09:48:53.494 # Redis version=5.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1   | 1:C 22 Mar 2020 09:48:53.494 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
mysql_1   | 2020-03-22 09:48:53+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.29-1debian10 started.
mysql_1   | 2020-03-22 09:48:54+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
redis_1   | 1:M 22 Mar 2020 09:48:53.496 * Running mode=standalone, port=6379.
mysql_1   | 2020-03-22 09:48:54+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.29-1debian10 started.
mysql_1   | 2020-03-22 09:48:54+00:00 [Note] [Entrypoint]: Initializing database files
redis_1   | 1:M 22 Mar 2020 09:48:53.497 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1   | 1:M 22 Mar 2020 09:48:53.497 # Server initialized
redis_1   | 1:M 22 Mar 2020 09:48:53.497 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
mysql_1   | mysqld: [Warning] World-writable config file '/etc/mysql/my.cnf' is ignored.
mysql_1   | 2020-03-22T09:48:54.529158Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
mysql_1   | 2020-03-22T09:48:54.543824Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
mysql_1   | 2020-03-22T09:48:54.543858Z 0 [ERROR] Aborting
mysql_1   |
redis_1   | 1:M 22 Mar 2020 09:48:53.504 * DB loaded from disk: 0.006 seconds
chatapp_mysql_1 exited with code 1
django_1  | Traceback (most recent call last):
django_1  |   File "manage.py", line 8, in <module>
django_1  |     from django.core.management import execute_from_command_line
django_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 14, in <module>
django_1  |     from django.core.management.base import (
django_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 11, in <module>
django_1  |     from django.core import checks
django_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/checks/__init__.py", line 8, in <module>
django_1  |     import django.core.checks.caches  # NOQA isort:skip
django_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/checks/caches.py", line 2, in <module>
django_1  |     from django.core.cache import DEFAULT_CACHE_ALIAS
django_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/cache/__init__.py", line 15, in <module>
django_1  |     from asgiref.local import Local
django_1  | ModuleNotFoundError: No module named 'asgiref.local'
django_1  |
django_1  | The above exception was the direct cause of the following exception:
django_1  |
django_1  | Traceback (most recent call last):
django_1  |   File "manage.py", line 14, in <module>
django_1  |     ) from exc
django_1  | ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
django_1  | Traceback (most recent call last):
django_1  |   File "manage.py", line 8, in <module>
django_1  |     from django.core.management import execute_from_command_line
django_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 14, in <module>
django_1  |     from django.core.management.base import (
django_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 11, in <module>
django_1  |     from django.core import checks
django_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/checks/__init__.py", line 8, in <module>
django_1  |     import django.core.checks.caches  # NOQA isort:skip
django_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/checks/caches.py", line 2, in <module>
django_1  |     from django.core.cache import DEFAULT_CACHE_ALIAS
django_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/cache/__init__.py", line 15, in <module>
django_1  |     from asgiref.local import Local
django_1  | ModuleNotFoundError: No module named 'asgiref.local'
django_1  |
django_1  | The above exception was the direct cause of the following exception:
django_1  |
django_1  | Traceback (most recent call last):
django_1  |   File "manage.py", line 14, in <module>
django_1  |     ) from exc
django_1  | ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
django_1  | Traceback (most recent call last):
django_1  |   File "manage.py", line 8, in <module>
django_1  |     from django.core.management import execute_from_command_line
django_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 14, in <module>
django_1  |     from django.core.management.base import (
django_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 11, in <module>
django_1  |     from django.core import checks
django_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/checks/__init__.py", line 8, in <module>
django_1  |     import django.core.checks.caches  # NOQA isort:skip
django_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/checks/caches.py", line 2, in <module>
django_1  |     from django.core.cache import DEFAULT_CACHE_ALIAS
django_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/cache/__init__.py", line 15, in <module>
django_1  |     from asgiref.local import Local
django_1  | ModuleNotFoundError: No module named 'asgiref.local'
django_1  |
django_1  | The above exception was the direct cause of the following exception:
django_1  |
django_1  | Traceback (most recent call last):
django_1  |   File "manage.py", line 14, in <module>
django_1  |     ) from exc
django_1  | ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
django_1  | *** Starting uWSGI 2.0.17.1 (64bit) on [Sun Mar 22 09:49:00 2020] ***
django_1  | compiled with version: 8.3.0 on 21 March 2020 16:22:10
django_1  | os: Linux-4.14.154-boot2docker #1 SMP Thu Nov 14 19:19:08 UTC 2019
django_1  | nodename: 13b9f3fbaaaa
django_1  | machine: x86_64
django_1  | clock source: unix
django_1  | pcre jit disabled
django_1  | detected number of CPU cores: 1
django_1  | current working directory: /server
django_1  | detected binary path: /usr/local/bin/uwsgi
django_1  | uWSGI running as root, you can use --uid/--gid/--chroot options
django_1  | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
django_1  | *** WARNING: you are running uWSGI without its master process manager ***
django_1  | your memory page size is 4096 bytes
django_1  | detected max file descriptor number: 1048576
django_1  | lock engine: pthread robust mutexes
django_1  | thunder lock: disabled (you can enable it with --thunder-lock)
django_1  | uwsgi socket 0 bound to TCP address :8001 fd 3
django_1  | uWSGI running as root, you can use --uid/--gid/--chroot options
django_1  | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
django_1  | Python version: 3.6.10 (default, Feb 26 2020, 16:13:33)  [GCC 8.3.0]
django_1  | *** Python threads support is disabled. You can enable it with --enable-threads ***
django_1  | Python main interpreter initialized at 0x55fd30e0bdb0
django_1  | uWSGI running as root, you can use --uid/--gid/--chroot options
django_1  | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
django_1  | your server socket listen backlog is limited to 100 connections
django_1  | your mercy for graceful operations on workers is 60 seconds
django_1  | mapped 72920 bytes (71 KB) for 1 cores
django_1  | *** Operational MODE: single process ***
django_1  | Traceback (most recent call last):
django_1  |   File "./chat_demo/wsgi.py", line 12, in <module>
django_1  |     from django.core.wsgi import get_wsgi_application
django_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/wsgi.py", line 2, in <module>
django_1  |     from django.core.handlers.wsgi import WSGIHandler
django_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 6, in <module>
django_1  |     from django.core.handlers import base
django_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 7, in <module>
django_1  |     from django.db import connections, transaction
django_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/__init__.py", line 2, in <module>
django_1  |     from django.db.utils import (
django_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 5, in <module>
django_1  |     from asgiref.local import Local
django_1  | ModuleNotFoundError: No module named 'asgiref.local'
django_1  | unable to load app 0 (mountpoint='') (callable not found or import error)
django_1  | *** no app loaded. going in full dynamic mode ***
django_1  | uWSGI running as root, you can use --uid/--gid/--chroot options
django_1  | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
django_1  | *** uWSGI is running in multiple interpreter mode ***
django_1  | spawned uWSGI worker 1 (and the only) (pid: 10, cores: 1)
django_1  | Traceback (most recent call last):
django_1  |   File "/usr/local/bin/daphne", line 8, in <module>
django_1  |     sys.exit(CommandLineInterface.entrypoint())
django_1  |   File "/usr/local/lib/python3.6/site-packages/daphne/cli.py", line 147, in entrypoint
django_1  |     cls().run(sys.argv[1:])
django_1  |   File "/usr/local/lib/python3.6/site-packages/daphne/cli.py", line 177, in run
django_1  |     application = import_by_path(args.application)
django_1  |   File "/usr/local/lib/python3.6/site-packages/daphne/utils.py", line 12, in import_by_path
django_1  |     target = importlib.import_module(module_path)
django_1  |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
django_1  |     return _bootstrap._gcd_import(name[level:], package, level)
django_1  |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
django_1  |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
django_1  |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
django_1  |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
django_1  |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
django_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
django_1  |   File "./chat_demo/asgi.py", line 4, in <module>
django_1  |     from channels.routing import get_default_application
django_1  |   File "/usr/local/lib/python3.6/site-packages/channels/routing.py", line 7, in <module>
django_1  |     from django.urls.exceptions import Resolver404
django_1  |   File "/usr/local/lib/python3.6/site-packages/django/urls/__init__.py", line 1, in <module>
django_1  |     from .base import (
django_1  |   File "/usr/local/lib/python3.6/site-packages/django/urls/base.py", line 3, in <module>
django_1  |     from asgiref.local import Local
django_1  | ModuleNotFoundError: No module named 'asgiref.local'
chatapp_django_1 exited with code 1
```

**Comment by infinity0206** [comment]
なんかよくわからんけど動くようになりました
